permalink: /:title

title: 半瓶子晃荡
url: https://liuzhy.com
feed: /atom.xml
author_info: <a href="https://liuzhy.com/">Liu Zhengyu</a>

# Comments
comments:
  provider: disqus
disqus: 
  short_name: liuzhy