# Site settings
title: 半瓶子晃悠
description: "专业修理电脑"
url: "https://liuzhy.com"
author:
  name: "Zhengyu Liu"
  email: "liuzhy@gmail.com"
  url: "https://liuzhy.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page:num/


# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: true

# Comments
comments:
  provider: disqus
disqus: 
  short_name: liuzhy
